version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /root/backend/static/:/app/static/
    ports:
      - "8000:8000"
    networks:
      eip-net:
        ipv4_address: 172.20.0.13

  ai_model:


networks:
  eip-net:
    external: true