"""update db

Revision ID: 03a38dff1c0d
Revises: 3f791d638865
Create Date: 2024-08-24 23:17:49.403564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a38dff1c0d'
down_revision: Union[str, None] = '3f791d638865'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    op.drop_table('frame_video')
    op.add_column('video_path', sa.Column('power_state', sa.Integer(), nullable=True))
    op.add_column('video_path', sa.Column('throws', sa.Integer(), nullable=True))
    op.add_column('video_path', sa.Column('empty_state', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_path', 'empty_state')
    op.drop_column('video_path', 'throws')
    op.drop_column('video_path', 'power_state')
    op.create_table('frame_video',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('frame_path', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('power_state', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('throws', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('empty_state', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video_path.id'], name='frame_video_video_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='frame_video_pkey')
    )
    op.create_table('stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_states', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video_path.id'], name='stats_video_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stats_pkey')
    )
    # ### end Alembic commands ###
