"""update table2

Revision ID: 0ec0830d71ff
Revises: a413ee8d0983
Create Date: 2024-08-25 00:20:47.739427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec0830d71ff'
down_revision: Union[str, None] = 'a413ee8d0983'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_path', sa.Column('power_state', sa.Integer(), nullable=True))
    op.add_column('video_path', sa.Column('throws', sa.Integer(), nullable=True))
    op.add_column('video_path', sa.Column('empty_state', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_path', 'empty_state')
    op.drop_column('video_path', 'throws')
    op.drop_column('video_path', 'power_state')
    # ### end Alembic commands ###
