"""add description column

Revision ID: 311bde61aa05
Revises: f5e8068189ad
Create Date: 2024-08-25 07:36:30.957089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '311bde61aa05'
down_revision: Union[str, None] = 'f5e8068189ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('frame_video', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('frame_video', 'description')
    # ### end Alembic commands ###
