"""update nullalble video_path

Revision ID: 64922575b146
Revises: 03b3e8745199
Create Date: 2024-08-25 14:01:50.613967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64922575b146'
down_revision: Union[str, None] = '03b3e8745199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_path', sa.Column('power_total', sa.Integer(), nullable=True))
    op.add_column('video_path', sa.Column('throws_total', sa.Integer(), nullable=True))
    op.add_column('video_path', sa.Column('safes_total', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_path', 'safes_total')
    op.drop_column('video_path', 'throws_total')
    op.drop_column('video_path', 'power_total')
    # ### end Alembic commands ###
