"""update table

Revision ID: 6abbcc7c74e1
Revises: d78c40472903
Create Date: 2024-08-25 00:18:25.721176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6abbcc7c74e1'
down_revision: Union[str, None] = 'd78c40472903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_frame', sa.Column('video_path', sa.Integer(), nullable=False))
    op.drop_constraint('video_frame_video_id_fkey', 'video_frame', type_='foreignkey')
    op.create_foreign_key(None, 'video_frame', 'video_path', ['video_path'], ['id'])
    op.drop_column('video_frame', 'video_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_frame', sa.Column('video_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'video_frame', type_='foreignkey')
    op.create_foreign_key('video_frame_video_id_fkey', 'video_frame', 'video_path', ['video_id'], ['id'])
    op.drop_column('video_frame', 'video_path')
    # ### end Alembic commands ###
