"""update table2

Revision ID: a413ee8d0983
Revises: e1dcc10fa463
Create Date: 2024-08-25 00:20:15.734975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a413ee8d0983'
down_revision: Union[str, None] = 'e1dcc10fa463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_frame')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_frame',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('power_state', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('throws', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('empty_state', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('video_path', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['video_path'], ['video_path.id'], name='video_frame_video_path_fkey'),
    sa.PrimaryKeyConstraint('id', name='video_frame_pkey')
    )
    # ### end Alembic commands ###
