"""update table2

Revision ID: c59397104e9e
Revises: 0ec0830d71ff
Create Date: 2024-08-25 05:48:44.810981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c59397104e9e'
down_revision: Union[str, None] = '0ec0830d71ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frame_video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('frame_path', sa.String(), nullable=True),
    sa.Column('power_state', sa.Integer(), nullable=True),
    sa.Column('throws_state', sa.Integer(), nullable=True),
    sa.Column('empty_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video_path.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('video_path', sa.Column('path', sa.String(), nullable=True))
    op.drop_column('video_path', 'empty_state')
    op.drop_column('video_path', 'throws')
    op.drop_column('video_path', 'power_state')
    op.drop_column('video_path', 'video_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_path', sa.Column('video_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('video_path', sa.Column('power_state', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('video_path', sa.Column('throws', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('video_path', sa.Column('empty_state', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('video_path', 'path')
    op.drop_table('frame_video')
    # ### end Alembic commands ###
