"""add new table VideoFrame

Revision ID: d78c40472903
Revises: 03a38dff1c0d
Create Date: 2024-08-25 00:00:49.139535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd78c40472903'
down_revision: Union[str, None] = '03a38dff1c0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_frame',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('frame_path', sa.String(), nullable=False),
    sa.Column('power_state', sa.Integer(), nullable=True),
    sa.Column('throws', sa.Integer(), nullable=True),
    sa.Column('empty_state', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['video_id'], ['video_path.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('video_path', sa.Column('video_name', sa.String(), nullable=True))
    op.drop_column('video_path', 'power_state')
    op.drop_column('video_path', 'throws')
    op.drop_column('video_path', 'empty_state')
    op.drop_column('video_path', 'path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_path', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('video_path', sa.Column('empty_state', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('video_path', sa.Column('throws', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('video_path', sa.Column('power_state', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('video_path', 'video_name')
    op.drop_table('video_frame')
    # ### end Alembic commands ###
