"""update table1

Revision ID: e1dcc10fa463
Revises: 6abbcc7c74e1
Create Date: 2024-08-25 00:18:56.176561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1dcc10fa463'
down_revision: Union[str, None] = '6abbcc7c74e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_frame', 'frame_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_frame', sa.Column('frame_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
